// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.2.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// --------- //
// fifo_echo //
// --------- //

#define fifo_echo_wrap_target 0
#define fifo_echo_wrap 4
#define fifo_echo_pio_version 1

static const uint16_t fifo_echo_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block
    0xa027, //  1: mov    x, osr
    0xa0c1, //  2: mov    isr, x
    0x8020, //  3: push   block
    0x0000, //  4: jmp    0
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program fifo_echo_program = {
    .instructions = fifo_echo_program_instructions,
    .length = 5,
    .origin = -1,
    .pio_version = fifo_echo_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config fifo_echo_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + fifo_echo_wrap_target, offset + fifo_echo_wrap);
    return c;
}
#endif

// --------- //
// read_pins //
// --------- //

#define read_pins_wrap_target 0
#define read_pins_wrap 2
#define read_pins_pio_version 1

static const uint16_t read_pins_program_instructions[] = {
            //     .wrap_target
    0x4010, //  0: in     pins, 16
    0x8020, //  1: push   block
    0x0000, //  2: jmp    0
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program read_pins_program = {
    .instructions = read_pins_program_instructions,
    .length = 3,
    .origin = -1,
    .pio_version = read_pins_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config read_pins_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + read_pins_wrap_target, offset + read_pins_wrap);
    return c;
}
#endif

// ------------- //
// push_on_match //
// ------------- //

#define push_on_match_wrap_target 0
#define push_on_match_wrap 7
#define push_on_match_pio_version 1

static const uint16_t push_on_match_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block
    0xa027, //  1: mov    x, osr
    0xa0c3, //  2: mov    isr, null
    0x4010, //  3: in     pins, 16
    0xa046, //  4: mov    y, isr
    0x00a0, //  5: jmp    x != y, 0
    0x8020, //  6: push   block
    0x0000, //  7: jmp    0
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program push_on_match_program = {
    .instructions = push_on_match_program_instructions,
    .length = 8,
    .origin = -1,
    .pio_version = push_on_match_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config push_on_match_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + push_on_match_wrap_target, offset + push_on_match_wrap);
    return c;
}
#endif

// ------------------ //
// irq_on_match_sync0 //
// ------------------ //

#define irq_on_match_sync0_wrap_target 0
#define irq_on_match_sync0_wrap 11
#define irq_on_match_sync0_pio_version 1

static const uint16_t irq_on_match_sync0_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block
    0xa027, //  1: mov    x, osr
    0xa0c3, //  2: mov    isr, null
    0x4010, //  3: in     pins, 16
    0xa046, //  4: mov    y, isr
    0x00a0, //  5: jmp    x != y, 0
    0xc000, //  6: irq    nowait 0
    0xa0c3, //  7: mov    isr, null
    0x4010, //  8: in     pins, 16
    0xa046, //  9: mov    y, isr
    0x00a0, // 10: jmp    x != y, 0
    0x0007, // 11: jmp    7
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program irq_on_match_sync0_program = {
    .instructions = irq_on_match_sync0_program_instructions,
    .length = 12,
    .origin = -1,
    .pio_version = irq_on_match_sync0_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config irq_on_match_sync0_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + irq_on_match_sync0_wrap_target, offset + irq_on_match_sync0_wrap);
    return c;
}
#endif

// ----------------- //
// irq_on_match_sync //
// ----------------- //

#define irq_on_match_sync_wrap_target 0
#define irq_on_match_sync_wrap 7
#define irq_on_match_sync_pio_version 1

static const uint16_t irq_on_match_sync_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block
    0xa027, //  1: mov    x, osr
    0xa040, //  2: mov    y, pins
    0x00a2, //  3: jmp    x != y, 2
    0xc020, //  4: irq    wait 0
    0xa040, //  5: mov    y, pins
    0x00a2, //  6: jmp    x != y, 2
    0x0005, //  7: jmp    5
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program irq_on_match_sync_program = {
    .instructions = irq_on_match_sync_program_instructions,
    .length = 8,
    .origin = -1,
    .pio_version = irq_on_match_sync_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config irq_on_match_sync_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + irq_on_match_sync_wrap_target, offset + irq_on_match_sync_wrap);
    return c;
}
#endif

