// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.2.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ----------- //
// iohost_read //
// ----------- //

#define iohost_read_wrap_target 0
#define iohost_read_wrap 4
#define iohost_read_pio_version 1

static const uint16_t iohost_read_program_instructions[] = {
            //     .wrap_target
    0x4010, //  0: in     pins, 16
    0xa026, //  1: mov    x, isr
    0x00a4, //  2: jmp    x != y, 4
    0xc000, //  3: irq    nowait 0
    0x0000, //  4: jmp    0
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program iohost_read_program = {
    .instructions = iohost_read_program_instructions,
    .length = 5,
    .origin = -1,
    .pio_version = iohost_read_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config iohost_read_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + iohost_read_wrap_target, offset + iohost_read_wrap);
    return c;
}

uint iohost_read_program_init(
    PIO pio,
    uint sm,
    uint offset,
    uint first_pin,
    uint pattern
) {
    // Configure 16 pins as inputs
    for (int i = 0; i < 16; i++)
        pio_gpio_init(pio, first_pin + i);
    pio_sm_set_consecutive_pindirs(pio, sm, first_pin, 16, false);
    // Configure shift registers
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_in_pins(&c, first_pin);
    sm_config_set_in_shift(&c, true, true, 16);  // shift right, autopush, 16
    // Load program
    pio_sm_init(pio, sm, offset, &c);
    // Push pattern into OSR
    pio_sm_put_blocking(pio, sm, pattern);
    // Enable IRQ0 from this PIO
    pio_set_irq0_source_enabled(pio, pis_interrupt0, true);
    // Start state machine
    pio_sm_set_enabled(pio, sm, true);
    return offset;
}

#endif

