// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.2.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ----- //
// break //
// ----- //

#define break_wrap_target 0
#define break_wrap 10
#define break_pio_version 1

static const uint16_t break_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block
    0xa027, //  1: mov    x, osr
    0xa040, //  2: mov    y, pins
    0x00a2, //  3: jmp    x != y, 2
    0xa0c2, //  4: mov    isr, y
    0x8000, //  5: push   noblock
    0xd000, //  6: irq    nowait 0        side 0
    0x80a0, //  7: pull   block
    0xb842, //  8: nop                    side 1
    0x8020, //  9: push   block
    0x0000, // 10: jmp    0
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program break_program = {
    .instructions = break_program_instructions,
    .length = 11,
    .origin = -1,
    .pio_version = break_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config break_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + break_wrap_target, offset + break_wrap);
    sm_config_set_sideset(&c, 2, true, true);
    return c;
}
#endif

